<a href="https://colab.research.google.com/github/jahnavitelsang/DATASCIENCE/blob/main/PYTHON.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PYTHON**

# **INPUT FUNCTION**

In [ ]:
variable = input()

In [ ]:
name = input("enter the name : ")
print(name)
print("hello", name)

In [ ]:
age = input("enter the age :")
print("the age is ", age)
type(age)

In [ ]:
age = int(input("enter the age :"))
print("the age is ", age)
type(age)

In [ ]:
age = float(input("enter the age :"))
print("the age is ", age)
type(age)

In [ ]:
temp = float(input("enter the temp :"))
print("the temp is ", age)
type(age)

# **DATA STRUCTURES**

# **LISTS------- pass all data types**

In [ ]:
l1 = [17,89,18,78]  #int#
l2 = [4.7,9.0,4.5]   #float#
l3 = ['hello',1,3.89,True]  #mixed#
print(l1,l2,l3)

In [ ]:
l4 = []
print(l4)

# **INDEXING**

In [ ]:
lt1 = [2,4,5,6,7,8]
lt1[0]
print(lt1[0])
print(lt1[5])

In [ ]:
lt1 = [2,4,5,6,7,8]
lt1[-1]
print(lt1[-1])
print(lt1[-3])

# **MUTUABLE**

## **IF IDS ARE SAME THEN MUTUABLE** ---- id1=id2

In [ ]:
l = [1,3,4,5,6,7,'apple']
print(id(l))

In [ ]:
l[1] = 'banana'
l[-3] = True
print(l)
id(l)

In [ ]:
p = [1,2,3,4]
print(id(p))

In [ ]:
p[0]= True
print(p)
id(p)

# **ALLOWS DUPLICATE**

# **ALLOWS MIXED DATATYPES AS WELL**

In [ ]:
name = [1,5.6,True,[1,1,1,1,1]]
print(name)

# **LIST METHODS**

In [ ]:
a = [2,3,4]
a

# **ADDING**

In [ ]:
a.append(90)
a

In [ ]:
a.insert(2,'orange')
a

In [ ]:
b = [1,3,4,'janu']
a.extend(b)
a

# REMOVING

In [ ]:
a = [2, 3, 'orange', 4, 90, 1, 3, 4, 'janu']
a.remove(3)
a

In [ ]:
a.pop() #removes and returns the last value#

In [ ]:
a.pop(4)    #removes and returns vale in pop#

In [ ]:
a.clear()
a

# OTHERS

In [ ]:
b = [2,3,4,5,6,7]
len(b)

In [ ]:
b.index(3)

In [ ]:
c = [3,3,3,5,8,9,0,4,5]
c.count(5)

In [ ]:
c.sort()
c

In [ ]:
c.reverse()
c

In [ ]:
#looping#
janu = ['mom','dad','brother']
for i in janu:
  print(i)

# **CHECKING THE MEMBERSHIP**

In [ ]:
colors = ['red','blue','green']
print('blue'in colors)
print('white'in colors)
print('purple'not in colors)

# **list slicing**

In [ ]:
num = ['a','b','c','d','e','f','g']
num

In [ ]:
num[:]

In [ ]:
num[::]

In [ ]:
num[:5:]

In [ ]:
num[::-1]

In [ ]:
num[5::]

In [ ]:
num[::3]

In [ ]:
num[-1:-4:-2]

In [ ]:
num[-3:-1]

# **TUPLE**

In [ ]:
t1 = ('apple',5.76,78,False)
t1

In [ ]:
type(t1)

In [ ]:
t2 = (1,2,3)
t2
type(t2)

In [ ]:
t3 = (1)
t3
type(t3)

# **ALWAYS USE COMMA WHEN USING SINGLE DIGIT AS TUPLE**

In [ ]:
t4 = (7,)
t4
type(t4)

PACKING AND UNPACKING

In [ ]:
a = 26
b = 90
t = (a,b)
print(t)

In [ ]:
x,y = t
print(x)
print(y)

In [ ]:
v = (7,8,9)
print(len(v))   # functionsssssssssssssssssssssssssssssssssssssssssss#
print(sum(v))
print(min(v))
print(max(v))

# **LIST INSIDE THE TUPLE IS MUTUABLE AND CAN BE CHANGED**

In [ ]:
w = (2,3,[6,7])
w[2][1] = 78
w

ACCESSING AND SLICLING OF TUPLE
# **Cannot be modified but can be accessed**

In [ ]:
w[0]

In [ ]:
f = (1,2,3,4)
f[0]

In [ ]:
f[::-1]

In [ ]:
f[1::]

In [ ]:
f[:2:]

In [ ]:
f[::2]

In [ ]:
f[3:4:]

# **TUPLE OPERATION**
CONCATATION
REPETATION
MEMBERSHIP

In [ ]:
e = ('v','o','p')  #concatation#
h = (3,4,5)
print(e+h)

In [ ]:
print(('e',)*3)  #repetation#

In [ ]:
print(3 in (4,5,6)) #membership3

# **TUPLE HAS 2 MAIN METHODS THAT IS COUNT AND INDEX**

# **CONVERT THE TUPLE TO LIST AND THEN MODIFY AND THEN CONVERY BACK TO TUPLE**

In [ ]:
a = (1,2,3,4)
a

In [ ]:
temp = list(a)
temp

In [ ]:
temp.append(5)
temp

In [ ]:
tuple(temp)

## **SET**

In [ ]:
s = {1,2,3,4}
s1 = {1,1,1,2,3,4,4,4,5,56}
s
s1

In [ ]:
s2 = {1,2.3,'python',False,(1,2,3,4)}
s2

In [ ]:
s3 = set([1,2,3,4])  #creating a set using set constructor#
s3

In [ ]:
s4 = set('hello')  # because of this there is no indexinga nd slicing bze it is unordered#
s4

In [ ]:
s5 = {}#                       always get a set through set constructor#
s5

In [ ]:
type(s5)

In [ ]:
s6 = set()
s6

In [ ]:
type(s6)

# **SET METHODS**

In [ ]:
s = {'apple', 'banana', 'cherry'}
s

In [ ]:
s.add('mango')
s

In [ ]:
s.add('apple')   #no duplicate allowed#
s

In [ ]:
s.update(['cheeku','orange'])
s

In [ ]:
s.remove('cheeku')
s

In [ ]:
s.remove('grape')
s

In [ ]:
s.discard('grape')       # best to use discard for set bze no errors#
s

In [ ]:
s.clear()
s

## **SET OPEREATIONS **

In [ ]:
k1 = {1,2,3,4}
k2 = {3,4,5,6,7}
o = k1.union(k2)
o

In [ ]:
o1 = k1.intersection(k2)
o1

In [ ]:
o3 = k1.difference(k2)
o3

In [ ]:
o4 = k2.difference(k1)
o4

In [ ]:
o5 = k1.symmetric_difference(k2)
o5

# **DICTIONARY**

In [ ]:
d = {'name':'janu', 'age':25}
d

Creating a dict in multiple ways

In [ ]:
d1 = {}
d1

In [ ]:
d2 = dict()
d2

In [ ]:
d3 = dict(name='jane',age=25)
d3

In [ ]:
d4 = dict([('name','jane'),('age',25)])    # CREATING A LIST OF TUPLES#
d4

MUTUALIBILITY IN DICT

In [ ]:
i = {'name':'jane', 'city':'belgaum'}
i

In [ ]:
id(i)

In [ ]:
i['city'] = 'bangalore'
i

In [ ]:
id(i)          #ID1===ID2#

In [ ]:
s = {'name':'alice'}
s['name'] = 'jane'
s['age'] = 25
s

In [ ]:
s.update({'name':'janu', 'age':22, 'grade':'a'})
s

# **ACCESSING**

In [ ]:
s3 = {'name':'jane','grade':'a'}
s3

In [ ]:
s3['name']

In [ ]:
s3['city']

In [ ]:
s3.get('grade')

In [ ]:
s3.get('city')

# **BUILTIN FUNS**

In [ ]:
s4 = {'name':'jane','grade':'a'}
s4

In [ ]:
print(s4.keys())

In [ ]:
print(s4.values())

In [ ]:
print(s4.items())

# **POP FUNCTION** --------- pop removes the key which is passes and popitem removes the last item by default

In [ ]:
s = {'name':'jane','grade':'a','course':'ds'}

In [ ]:
s

In [ ]:
s.pop('name')
s

In [ ]:
s.popitem()
s

# **dict comprensation**

In [ ]:
d = {x:x**2  for x in range(1,6)}
d

In [ ]:
school = {
    'student' :{'name':"jane", 'class':12},
    'student1' : {'name':'janu','class':11}
}
school                                                                                  # NESTED DICT #

In [ ]:
print(school['student']['class'])

In [ ]:
age = int(input('enter the age:'))
if age >= 18:
  print('adult')
else:
  print('minor')

In [ ]:
for i in range(10):
  print(i)

In [ ]:
num = 0
while num < 5 :
  print(num)
  num += 1
num

In [ ]:
def square(num):
  return num*num

print(square(4))

# **NUMPY AND PANDAS**

NUMPY

In [1]:
import numpy as np

In [2]:
sum = np.array([12,23,34,45,67,78])   # 1D array#
sum

array([12, 23, 34, 45, 67, 78])

In [3]:
sum.shape

(6,)

In [4]:
sum1 = np.array([[12],[89],[45],[56]])     #2D array#
sum1

array([[12],
       [89],
       [45],
       [56]])

In [5]:
sum1.shape

(4, 1)

In [6]:
data = np.array([[12,23,23,34],[67,64,31,23],[637,84,920,84],[97,342,26,68]])
data

array([[ 12,  23,  23,  34],
       [ 67,  64,  31,  23],
       [637,  84, 920,  84],
       [ 97, 342,  26,  68]])

In [7]:
data.shape

(4, 4)

In [8]:
sp = data[:,0:1]
sp

array([[ 12],
       [ 67],
       [637],
       [ 97]])

In [9]:
print(np.mean(data[:,0:1]))

203.25

In [10]:
print(np.median(data[:,0:1]))

82.0

In [11]:
print(np.std(data[:,0:1]))

252.27403255190575

In [12]:
print(np.var(data[:,0:1]))

63642.1875

In [13]:
print(sp.mean())

203.25

In [18]:
print(data[:,0:2])

[[ 12  23]
 [ 67  64]
 [637  84]
 [ 97 342]]

In [24]:
print(data[:,0:3:2])

[[ 12  23]
 [ 67  31]
 [637 920]
 [ 97  26]]

CREATING RANDOM NUMBERS IN 1D

In [26]:
x = np.random.randint(10,20,size=10)
x

array([14, 13, 11, 17, 11, 14, 19, 13, 13, 17])

In [27]:
x.ndim

1

In [29]:
x1 = np.random.randint(10,20,size=(2,3))
x1

array([[16, 13, 13],
       [10, 19, 10]])

In [30]:
x1.ndim

2

In [31]:
x4 = np.random.randint(10,20,size=(3,3,4))
x4

array([[[13, 16, 11, 12],
        [17, 11, 16, 18],
        [13, 14, 16, 12]],

       [[16, 17, 11, 14],
        [13, 16, 18, 17],
        [17, 19, 16, 16]],

       [[16, 19, 18, 14],
        [19, 11, 18, 10],
        [18, 18, 19, 12]]])

In [32]:
x4.ndim

3

In [34]:
import pandas as pd

In [35]:
a = [1,2,3,4,5]
s = pd.Series(a)
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

dataframe=====2d array table in the form of rows and colimns

In [38]:
a = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])
print(a)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [39]:
df = pd.read_csv("/content/nyc_Jan_Jun_2016_weat.csv")

In [42]:
df.head()

       DATE  LATITUDE  LONGITUDE  SNOW  PRCP    SNWD  TAVG  TMAX  TMIN
0  20160101   41.0639   -73.7722   0.0   0.0 -9999.0 -9999 -9999 -9999
1  20160102   41.0639   -73.7722   0.0   0.0 -9999.0 -9999 -9999 -9999
2  20160103   41.0639   -73.7722   0.0   0.0 -9999.0 -9999 -9999 -9999
3  20160104   41.0639   -73.7722   0.0   0.0 -9999.0 -9999 -9999 -9999
4  20160105   41.0639   -73.7722   0.0   0.0 -9999.0 -9999 -9999 -9999

In [43]:
df.shape

(32207, 9)

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32207 entries, 0 to 32206
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   DATE       32207 non-null  int64
 1   LATITUDE   32207 non-null  float64
 2   LONGITUDE  32207 non-null  float64
 3   SNOW       32207 non-null  float64
 4   PRCP       32207 non-null  float64
 5   SNWD       32207 non-null  float64
 6   TAVG       32207 non-null  int64
 7   TMAX       32207 non-null  int64
 8   TMIN       32207 non-null  int64
dtypes: float64(5), int64(4)
memory usage: 2.2 MB

In [45]:
df.describe()

,DATE,LATITUDE,LONGITUDE,SNOW,PRCP,SNWD,TAVG,TMAX,TMIN
count,3.220700e+04,32207.000000,32207.000000,32207.000000,32207.000000,32207.000000,32207.000000,32207.000000,32207.000000
mean,2.016379e+07,40.758364,-74.115480,-4263.479085,-41.474001,-7452.434185,-9472.630453,-7806.498743,-7798.696184
std,4.553580e+03,0.210378,0.250133,4945.177190,643.636786,4356.649666,2239.591076,4153.806872,4154.587650
min,2.016010e+07,40.275400,-74.482700,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000
25%,2.016051e+07,40.662300,-74.284700,-9999.000000,0.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000
50%,2.016092e+07,40.755600,-74.152300,0.000000,0.000000,-9999.000000,-9999.000000,-9999.000000,-9999.000000
75%,2.017021e+07,40.902700,-74.000200,0.000000,0.070000,0.000000,-9999.000000,-9999.000000,-9999.000000
max,2.017072e+07,41.083500,-73.372200,68.000000,17.760000,30.700000,91.000000,101.000000,84.000000

In [49]:
df['LATITUDE'].head()

0    41.0639
1    41.0639
2    41.0639
3    41.0639
4    41.0639
Name: LATITUDE, dtype: float64

In [54]:
df[['LONGITUDE','PRCP']].head()

   LONGITUDE  PRCP
0   -73.7722   0.0
1   -73.7722   0.0
2   -73.7722   0.0
3   -73.7722   0.0
4   -73.7722   0.0

LOC AND ILOC CONCEPT

In [56]:
df.loc[0:4,['LONGITUDE','PRCP	']]  #          using the lables as well #

   LONGITUDE  PRCP
0   -73.7722   0.0
1   -73.7722   0.0
2   -73.7722   0.0
3   -73.7722   0.0
4   -73.7722   0.0

In [57]:
df.loc[[0,4,7],['LONGITUDE','PRCP']]

   LONGITUDE  PRCP
0   -73.7722   0.0
4   -73.7722   0.0
7   -73.7722   0.0

In [64]:
df.loc[0:6,'LONGITUDE':'SNWD']

   LONGITUDE  SNOW  PRCP    SNWD
0   -73.7722   0.0   0.0 -9999.0
1   -73.7722   0.0   0.0 -9999.0
2   -73.7722   0.0   0.0 -9999.0
3   -73.7722   0.0   0.0 -9999.0
4   -73.7722   0.0   0.0 -9999.0
5   -73.7722   0.0   0.0 -9999.0
6   -73.7722   0.0   0.0 -9999.0

In [66]:
df.iloc[:,0:5].head()             # using only the intergers that is by rows and columns#

       DATE  LATITUDE  LONGITUDE  SNOW  PRCP
0  20160101   41.0639   -73.7722   0.0   0.0
1  20160102   41.0639   -73.7722   0.0   0.0
2  20160103   41.0639   -73.7722   0.0   0.0
3  20160104   41.0639   -73.7722   0.0   0.0
4  20160105   41.0639   -73.7722   0.0   0.0

In [67]:
df.iloc[0:8,2:5]

   LONGITUDE  SNOW  PRCP
0   -73.7722   0.0   0.0
1   -73.7722   0.0   0.0
2   -73.7722   0.0   0.0
3   -73.7722   0.0   0.0
4   -73.7722   0.0   0.0
5   -73.7722   0.0   0.0
6   -73.7722   0.0   0.0
7   -73.7722   0.0   0.0

In [68]:
df.iloc[2:15,[1,6,8]]

    LATITUDE  TAVG  TMIN
2    41.0639 -9999 -9999
3    41.0639 -9999 -9999
4    41.0639 -9999 -9999
5    41.0639 -9999 -9999
6    41.0639 -9999 -9999
7    41.0639 -9999 -9999
8    41.0639 -9999 -9999
9    41.0639 -9999 -9999
10   41.0639 -9999 -9999
11   41.0639 -9999 -9999
12   41.0639 -9999 -9999
13   41.0639 -9999 -9999
14   41.0639 -9999 -9999

In [70]:
df.iloc[[1,2,4,5],4:8]

   PRCP    SNWD  TAVG  TMAX
1   0.0 -9999.0 -9999 -9999
2   0.0 -9999.0 -9999 -9999
4   0.0 -9999.0 -9999 -9999
5   0.0 -9999.0 -9999 -9999

In [71]:
df[df['TMAX']>100].head()

          DATE  LATITUDE  LONGITUDE  SNOW  PRCP  SNWD  TAVG  TMAX  TMIN
4938  20170613   40.7792     -73.88   0.0   0.0   0.0    90   101    80

In [72]:
df[df['PRCP']<100].head()

       DATE  LATITUDE  LONGITUDE  SNOW  PRCP    SNWD  TAVG  TMAX  TMIN
0  20160101   41.0639   -73.7722   0.0   0.0 -9999.0 -9999 -9999 -9999
1  20160102   41.0639   -73.7722   0.0   0.0 -9999.0 -9999 -9999 -9999
2  20160103   41.0639   -73.7722   0.0   0.0 -9999.0 -9999 -9999 -9999
3  20160104   41.0639   -73.7722   0.0   0.0 -9999.0 -9999 -9999 -9999
4  20160105   41.0639   -73.7722   0.0   0.0 -9999.0 -9999 -9999 -9999

In [75]:
df[df['TAVG'] == -9999].head()

       DATE  LATITUDE  LONGITUDE  SNOW  PRCP    SNWD  TAVG  TMAX  TMIN
0  20160101   41.0639   -73.7722   0.0   0.0 -9999.0 -9999 -9999 -9999
1  20160102   41.0639   -73.7722   0.0   0.0 -9999.0 -9999 -9999 -9999
2  20160103   41.0639   -73.7722   0.0   0.0 -9999.0 -9999 -9999 -9999
3  20160104   41.0639   -73.7722   0.0   0.0 -9999.0 -9999 -9999 -9999
4  20160105   41.0639   -73.7722   0.0   0.0 -9999.0 -9999 -9999 -9999

In [76]:
df.sort_values(by='TAVG').head()   # for ascending sorting #

           DATE  LATITUDE  LONGITUDE  SNOW  PRCP    SNWD  TAVG  TMAX  TMIN
21653  20170709   40.4562   -74.2413   0.0   0.0 -9999.0 -9999 -9999 -9999
21668  20160109   40.6670   -74.4827   0.0   0.0 -9999.0 -9999 -9999 -9999
21667  20160108   40.6670   -74.4827   0.0   0.0 -9999.0 -9999 -9999 -9999
21666  20160107   40.6670   -74.4827   0.0   0.0 -9999.0 -9999 -9999 -9999
21665  20160106   40.6670   -74.4827   0.0   0.0 -9999.0 -9999 -9999 -9999

In [77]:
df.sort_values(by='TAVG',ascending=False).head()

          DATE  LATITUDE  LONGITUDE  SNOW  PRCP  SNWD  TAVG  TMAX  TMIN
4635  20160814   40.7792   -73.8800   0.0  0.01   0.0    91    98    81
4938  20170613   40.7792   -73.8800   0.0  0.00   0.0    90   101    80
4613  20160723   40.7792   -73.8800   0.0  0.00   0.0    89    99    82
4634  20160813   40.7792   -73.8800   0.0  0.00   0.0    89    98    84
6092  20160814   40.6825   -74.1694   0.0  0.00   0.0    89    97    80

In [80]:
df.isnull()

        DATE  LATITUDE  LONGITUDE   SNOW   PRCP   SNWD   TAVG   TMAX   TMIN
0      False     False      False  False  False  False  False  False  False
1      False     False      False  False  False  False  False  False  False
2      False     False      False  False  False  False  False  False  False
3      False     False      False  False  False  False  False  False  False
4      False     False      False  False  False  False  False  False  False
...      ...       ...        ...    ...    ...    ...    ...    ...    ...
32202  False     False      False  False  False  False  False  False  False
32203  False     False      False  False  False  False  False  False  False
32204  False     False      False  False  False  False  False  False  False
32205  False     False      False  False  False  False  False  False  False
32206  False     False      False  False  False  False  False  False  False

[32207 rows x 9 columns]

In [81]:
df.isnull().sum()

DATE         0
LATITUDE     0
LONGITUDE    0
SNOW         0
PRCP         0
SNWD         0
TAVG         0
TMAX         0
TMIN         0
dtype: int64

In [83]:
df.dropna().head()        #dropping null values#

       DATE  LATITUDE  LONGITUDE  SNOW  PRCP    SNWD  TAVG  TMAX  TMIN
0  20160101   41.0639   -73.7722   0.0   0.0 -9999.0 -9999 -9999 -9999
1  20160102   41.0639   -73.7722   0.0   0.0 -9999.0 -9999 -9999 -9999
2  20160103   41.0639   -73.7722   0.0   0.0 -9999.0 -9999 -9999 -9999
3  20160104   41.0639   -73.7722   0.0   0.0 -9999.0 -9999 -9999 -9999
4  20160105   41.0639   -73.7722   0.0   0.0 -9999.0 -9999 -9999 -9999

In [85]:
df.fillna(0)

           DATE  LATITUDE  LONGITUDE    SNOW  PRCP    SNWD  TAVG  TMAX  TMIN
0      20160101  41.06390  -73.77220     0.0  0.00 -9999.0 -9999 -9999 -9999
1      20160102  41.06390  -73.77220     0.0  0.00 -9999.0 -9999 -9999 -9999
2      20160103  41.06390  -73.77220     0.0  0.00 -9999.0 -9999 -9999 -9999
3      20160104  41.06390  -73.77220     0.0  0.00 -9999.0 -9999 -9999 -9999
4      20160105  41.06390  -73.77220     0.0  0.00 -9999.0 -9999 -9999 -9999
...         ...       ...        ...     ...   ...     ...   ...   ...   ...
32202  20170709  40.73417  -73.41694 -9999.0  0.00 -9999.0 -9999    82    67
32203  20170710  40.73417  -73.41694 -9999.0  0.00 -9999.0 -9999    81    64
32204  20170711  40.73417  -73.41694 -9999.0  0.06 -9999.0 -9999    86    74
32205  20170712  40.73417  -73.41694 -9999.0  0.00 -9999.0 -9999    90    74
32206  20170713  40.73417  -73.41694 -9999.0  0.01 -9999.0 -9999    91    68

[32207 rows x 9 columns]

# **GROUPING**

In [87]:
df.groupby('TMAX')['TMIN'].mean()

TMAX
-9999   -9979.048037
 12        -2.000000
 13        -3.000000
 14        -3.000000
 15        -1.000000
            ...
 97        74.875000
 98        76.727273
 99        73.400000
 100       77.500000
 101       80.000000
Name: TMIN, Length: 91, dtype: float64

In [13]:
import numpy as np
import pandas as pd

In [14]:
df = pd.read_csv('/content/market.csv')

In [15]:
df.head()

   Region       Product   Subsidiary  Stores  Sales  Inventory  Returns
0  Africa          Boot  Addis Ababa      12  29761     191821      769
1  Africa  Men's Casual  Addis Ababa       4  67242     118036     2284
2  Africa   Men's Dress  Addis Ababa       7  76793     136273     2433
3  Africa        Sandal  Addis Ababa      10  62819     204284     1861
4  Africa       Slipper  Addis Ababa      14  68641     279795     1771

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 390 entries, 0 to 389
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Region      390 non-null    object
 1   Product     390 non-null    object
 2   Subsidiary  390 non-null    object
 3   Stores      390 non-null    int64
 4   Sales       390 non-null    int64
 5   Inventory   390 non-null    int64
 6   Returns     390 non-null    int64
dtypes: int64(4), object(3)
memory usage: 21.5+ KB

In [17]:
df.describe()

           Stores          Sales     Inventory       Returns
count  390.000000     390.000000  3.900000e+02    390.000000
mean    11.502564   76313.023077  2.261371e+05   2659.658974
std      8.804868   95418.194363  2.679502e+05   3323.966711
min      1.000000     325.000000  3.740000e+02     10.000000
25%      3.000000   15124.500000  4.264050e+04    575.000000
50%     10.000000   38005.500000  1.181490e+05   1407.000000
75%     17.000000  104344.750000  3.280922e+05   3438.500000
max     41.000000  502636.000000  1.555357e+06  20470.000000

In [18]:
df.shape

(390, 7)

In [19]:
df.groupby('Region')['Sales'].sum()     # to get the region wise sales#

Region
Africa                       2342588
Asia                          460231
Canada                       2041054
Central America/Caribbean    3081641
Eastern Europe               2394940
Middle East                  4333062
Pacific                      2296794
South America                2434783
United States                5503986
Western Europe               4873000
Name: Sales, dtype: int64

In [23]:
df.groupby('Product')['Inventory'].sum()       # to get the how many are there in a product #

Product
Boot               9724671
Men's Casual      13044692
Men's Dress       12659781
Sandal             3232275
Slipper           19711295
Sport Shoe         3322702
Women's Casual     9696651
Women's Dress     16801392
Name: Inventory, dtype: int64

In [24]:
df.groupby('Region')['Sales'].mean()

Region
Africa                        41831.928571
Asia                          32873.642857
Canada                        60031.000000
Central America/Caribbean     99407.774194
Eastern Europe                77256.129032
Middle East                  188394.000000
Pacific                       51039.866667
South America                 45088.574074
United States                137599.650000
Western Europe                78596.774194
Name: Sales, dtype: float64

In [28]:
df.groupby(['Region','Product'])['Sales'].sum()

Region          Product
Africa          Boot              119835
                Men's Casual      562794
                Men's Dress       318500
                Sandal            190409
                Slipper           337076
                                   ...
Western Europe  Sandal             11349
                Slipper           857298
                Sport Shoe        201030
                Women's Casual    985647
                Women's Dress     827479
Name: Sales, Length: 80, dtype: int64

In [32]:
df.groupby(['Region','Stores'])['Sales'].mean()

Region          Stores
Africa          1          12759.800000
                2          27308.000000
                3          26457.166667
                4          43705.000000
                5          26962.666667
                              ...
Western Europe  23         88216.500000
                25        149354.000000
                26        502636.000000
                27        109808.000000
                31         54449.000000
Name: Sales, Length: 194, dtype: float64

In [35]:
df[df['Region'] == 'Africa'].head()

   Region       Product   Subsidiary  Stores  Sales  Inventory  Returns
0  Africa          Boot  Addis Ababa      12  29761     191821      769
1  Africa  Men's Casual  Addis Ababa       4  67242     118036     2284
2  Africa   Men's Dress  Addis Ababa       7  76793     136273     2433
3  Africa        Sandal  Addis Ababa      10  62819     204284     1861
4  Africa       Slipper  Addis Ababa      14  68641     279795     1771

In [36]:
df[df['Region'] != 'Africa'].head()

   Region         Product Subsidiary  Stores  Sales  Inventory  Returns
56   Asia            Boot    Bangkok       1   1996       9576       80
57   Asia     Men's Dress    Bangkok       1   3033      20831       52
58   Asia          Sandal    Bangkok       1   3230      15087      120
59   Asia         Slipper    Bangkok       1   3019      16075      127
60   Asia  Women's Casual    Bangkok       1   5389      16251      185