<a href="https://colab.research.google.com/github/jahnavitelsang/DATASCIENCE/blob/main/Recmsys.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#recommendation systems

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('/content/Movie.csv')

In [3]:
df.shape

(8992, 3)

In [4]:
df.head()

   userId             movie  rating
0       3  Toy Story (1995)     4.0
1       6  Toy Story (1995)     5.0
2       8  Toy Story (1995)     4.0
3      10  Toy Story (1995)     4.0
4      11  Toy Story (1995)     4.5

In [6]:
#Create a user-item matrix
user_df = df.pivot(index='userId',columns='movie',values='rating')
user_df.head()

movie,Father of the Bride Part II (1995),GoldenEye (1995),Grumpier Old Men (1995),Heat (1995),Jumanji (1995),Sabrina (1995),Sudden Death (1995),Tom and Huck (1995),Toy Story (1995),Waiting to Exhale (1995)
userId,,,,,,,,,,
1,NaN,NaN,NaN,NaN,3.5,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
4,NaN,4.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN

In [12]:
#input nans with 0 values
user_df.fillna(0,inplace=True)   # or i can also use user_df = user_df.fillna(0)
user_df.head()

movie,Father of the Bride Part II (1995),GoldenEye (1995),Grumpier Old Men (1995),Heat (1995),Jumanji (1995),Sabrina (1995),Sudden Death (1995),Tom and Huck (1995),Toy Story (1995),Waiting to Exhale (1995)
userId,,,,,,,,,,
1,0.0,0.0,0.0,0.0,3.5,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
4,0.0,4.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0

In [14]:
#compute user similarity
from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine,correlation

In [15]:
user_sim = 1-pairwise_distances(user_df.values,metric='cosine')
user_sim

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.55337157],
       [0.        , 1.        , 0.        , ..., 0.45883147, 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.45883147, 1.        ,
        0.62254302],
       ...,
       [0.        , 0.45883147, 0.45883147, ..., 1.        , 0.45883147,
        0.47607054],
       [0.        , 0.        , 1.        , ..., 0.45883147, 1.        ,
        0.62254302],
       [0.55337157, 0.        , 0.62254302, ..., 0.47607054, 0.62254302,
        1.        ]])

In [17]:
user_sim.shape

(4081, 4081)

In [18]:
np.fill_diagonal(user_sim,0)
user_sim

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.55337157],
       [0.        , 0.        , 0.        , ..., 0.45883147, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.45883147, 1.        ,
        0.62254302],
       ...,
       [0.        , 0.45883147, 0.45883147, ..., 0.        , 0.45883147,
        0.47607054],
       [0.        , 0.        , 1.        , ..., 0.45883147, 0.        ,
        0.62254302],
       [0.55337157, 0.        , 0.62254302, ..., 0.47607054, 0.62254302,
        0.        ]])

In [19]:
#store sim matrix
user_sim_df = pd.DataFrame(user_sim)
user_sim_df.head()

,0,1,2,3,4,5,6,7,8,9,...,4071,4072,4073,4074,4075,4076,4077,4078,4079,4080
0,0.0,0.0,0.0,0.0,1.0,0.000000,0.000000,0.000000,0.0,0.000000,...,0.0,0.0,1.0,0.707107,0.000000,0.0,0.000000,0.000000,0.0,0.553372
1,0.0,0.0,0.0,0.0,0.0,0.390567,0.707107,0.615457,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.458831,0.0,0.000000
2,0.0,0.0,0.0,0.0,0.0,0.650945,0.000000,0.492366,1.0,0.874157,...,0.0,1.0,0.0,0.707107,0.000000,0.0,0.752577,0.458831,1.0,0.622543
3,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.615457,0.0,0.388514,...,0.8,0.0,0.0,0.000000,0.989949,0.0,0.000000,0.619422,0.0,0.000000
4,1.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,...,0.0,0.0,1.0,0.707107,0.000000,0.0,0.000000,0.000000,0.0,0.553372

In [20]:
#now set index and coulmns names to user_id\
user_sim_df.index = df.userId.unique()
user_sim_df.columns = df.userId.unique()
user_sim_df.head()

,3,6,8,10,11,12,13,14,16,19,...,6975,6979,6993,7030,7031,7044,7070,7080,7087,7105
3,0.0,0.0,0.0,0.0,1.0,0.000000,0.000000,0.000000,0.0,0.000000,...,0.0,0.0,1.0,0.707107,0.000000,0.0,0.000000,0.000000,0.0,0.553372
6,0.0,0.0,0.0,0.0,0.0,0.390567,0.707107,0.615457,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.458831,0.0,0.000000
8,0.0,0.0,0.0,0.0,0.0,0.650945,0.000000,0.492366,1.0,0.874157,...,0.0,1.0,0.0,0.707107,0.000000,0.0,0.752577,0.458831,1.0,0.622543
10,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.615457,0.0,0.388514,...,0.8,0.0,0.0,0.000000,0.989949,0.0,0.000000,0.619422,0.0,0.000000
11,1.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,...,0.0,0.0,1.0,0.707107,0.000000,0.0,0.000000,0.000000,0.0,0.553372

In [22]:
user_sim_df.iloc[0:5,0:5]

     3    6    8    10   11
3   0.0  0.0  0.0  0.0  1.0
6   0.0  0.0  0.0  0.0  0.0
8   0.0  0.0  0.0  0.0  0.0
10  0.0  0.0  0.0  0.0  0.0
11  1.0  0.0  0.0  0.0  0.0

In [23]:
#identify most user similar
user_sim_df.idxmax(axis=1)[0:5]

3       11
6      168
8       16
10    4047
11       3
dtype: int64

In [24]:
#compare ratings of same user
df[(df['userId']==6) | (df['userId']==168)]

      userId                    movie  rating
1          6         Toy Story (1995)     5.0
60       168         Toy Story (1995)     4.5
3725       6  Grumpier Old Men (1995)     3.0
6464       6           Sabrina (1995)     5.0